name: Publish Packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish to Github
      uses: docker/build-push-action@v1
      with:
        username: timi137137
        password: ${{ secrets.GITHUBTOKEN }}
        registry: nuget.pkg.github.com
        repository: ${{ github.repository }}/AuroraNative
    - name: Publish to Nuget
        uses: rohith/publish-nuget@v2
        with:
            NUGET_KEY: ${{secrets.NUGETKEY}}